REPO_FOLDER = stream
MINI_FILES = stream.min.js stream.min.js.map
#STREAM_MINI_FILES := $(REPO_FOLDER)/stream.min.js $(REPO_FOLDER)/stream.min.js.map
STREAM_MINI_FILES := $(MINI_FILES:%=REPO_FOLDER/%) #6.3.1 Substitution References

stream.js.zip: $(STREAM_MINI_FILES)
	cd $(REPO_FOLDER); \
	npm run zip ../stream.js.zip $(MINI_FILES)

$(STREAM_MINI_FILES): minify

#$(REPO_FOLDER)/stream.min.js.map: minify

minify:
	@cd $(REPO_FOLDER); \
	test -d "node_modules" || npm install; \
	npm run minify;

update:
	@git submodule update --remote

all: update stream.js.zip

.PHONY: minify, update, all
